[package]
name = "encoder"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
indicatif = { version = "0.16", features = ["rayon"] }
rayon = "1.5"

encoder-lib = { path = "../encoder-lib" }
